-- ==========================================
-- SCRIPT DE REINICIO DE BASE DE DATOS
-- ==========================================
-- PRECAUCIÓN: Esto borrará TODOS los datos existentes.

DROP TABLE IF EXISTS reflections CASCADE;
DROP TABLE IF EXISTS habit_logs CASCADE;
DROP TABLE IF EXISTS habits CASCADE;
DROP TABLE IF EXISTS horarios CASCADE;
DROP TABLE IF EXISTS app_config CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS objectives CASCADE;
DROP TABLE IF EXISTS areas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- ==========================================

-- Tabla de usuarios (Custom Auth)
CREATE TABLE IF NOT EXISTS usuarios (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password_hash text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FASE 3: Novedades del Método Tsukuyomi

CREATE TABLE IF NOT EXISTS areas (
    id bigint generated by default as identity primary key,
    nombre text not null,
    vision text,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS objectives (
    id bigint generated by default as identity primary key,
    titulo text not null,
    estado text not null default 'Activo',
    area_id bigint references areas(id) on delete cascade,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS projects (
    id bigint generated by default as identity primary key,
    nombre text not null,
    estado text not null default 'Backlog', -- Backlog, Pendiente, En progreso, Completado, Pausado, Archivo
    objective_id bigint references objectives(id) on delete cascade,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS tasks (
    id bigint generated by default as identity primary key,
    titulo text not null,
    estado text not null default 'Pendiente', -- Pendiente, Completada
    project_id bigint references projects(id) on delete cascade,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FASE 4: SHUKAN (HÁBITOS)
CREATE TABLE IF NOT EXISTS habits (
    id bigint generated by default as identity primary key,
    nombre text not null,
    frecuencia text not null default 'Diario',
    objective_id bigint references objectives(id) on delete cascade,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS habit_logs (
    id bigint generated by default as identity primary key,
    habit_id bigint references habits(id) on delete cascade not null,
    fecha date not null,
    estado boolean not null default false,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(habit_id, fecha)
);

-- FASE 5: HANSEI (REFLEXIONES)
CREATE TABLE IF NOT EXISTS reflections (
    id bigint generated by default as identity primary key,
    tipo text not null, -- Diaria, Semanal, Mensual
    fecha date not null,
    respuestas jsonb not null,
    user_id bigint references usuarios(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Modificamos la tabla de horarios para anclar la alineación (Phase 3 y 4)
CREATE TABLE IF NOT EXISTS horarios (
    id bigint generated by default as identity primary key,
    actividad text not null,
    fase text not null,
    inicio text not null,
    fin text not null,
    categoria text not null,
    task_id bigint references tasks(id) on delete set null,
    habit_id bigint references habits(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id bigint references usuarios(id) on delete cascade not null
);

-- Tabla para guardar configuraciones de la aplicación (Fondo de pantalla personalizado)
CREATE TABLE IF NOT EXISTS app_config (
    key text,
    user_id bigint references usuarios(id) on delete cascade not null,
    value text not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (key, user_id)
);

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE horarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reflections ENABLE ROW LEVEL SECURITY;
