-- Crea la tabla para almacenar las actividades/horarios
CREATE TABLE IF NOT EXISTS horarios (
    id bigint generated by default as identity primary key,
    actividad text not null,
    fase text not null,
    inicio text not null,
    fin text not null,
    categoria text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS) opcional pero recomendado
ALTER TABLE horarios ENABLE ROW LEVEL SECURITY;

-- Al habilitar RLS sin políticas públicas, la tabla queda bloqueada por defecto.
-- Para que tu aplicación Streamlit pueda leer/escribir en esta tabla de forma segura:
-- Debes usar tu clave 'service_role' (secreta) en la variable SUPABASE_KEY de tu archivo .env.
-- Esto permite a tu backend (Streamlit) saltarse el RLS, mientras mantiene la base de datos protegida
-- de conexiones externas no autorizadas.
