-- Tabla de usuarios (Custom Auth)
CREATE TABLE IF NOT EXISTS usuarios (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password_hash text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Crea la tabla para almacenar las actividades/horarios
CREATE TABLE IF NOT EXISTS horarios (
    id bigint generated by default as identity primary key,
    actividad text not null,
    fase text not null,
    inicio text not null,
    fin text not null,
    categoria text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id bigint references usuarios(id) on delete cascade not null
);

-- Tabla para guardar configuraciones de la aplicación (Fondo de pantalla personalizado)
CREATE TABLE IF NOT EXISTS app_config (
    key text,
    user_id bigint references usuarios(id) on delete cascade not null,
    value text not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (key, user_id)
);

-- Como la seguridad se manejará en Python usando la llave service_role,
-- podemos deshabilitar RLS o simplemente crear políticas públicas 
-- para permitir que el service_role opere libremente.
-- Por seguridad básica, lo dejamos deshabilitado (ya que no usaremos llaves públicas)
-- o habilitado sin políticas (bloqueado para todos excepto service_role).
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE horarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
